export const AulasDesign = [
    { id: '1' , Type: 'Design', Title:'Design Thinking', Monitor:'Vinny', Image: require('./assets/design-covers/DSX-aula.png'), Link:'0m5yi7oJZ1M', PDF:'https://drive.google.com/file/d/1JaanbdUFJvrZeyL1Eixtit8PW-ILC86b/view', Lock:false,  week:0}, 
    { id: '2' , Type: 'Design', Title:'UX Design I', Monitor:'Ellis',  Image: require('./assets/design-covers/DSX-aula-1.png'), Link:'ffb-AuG8P5E', PDF:'https://drive.google.com/file/d/1v4tGRunHas4QhCCPyTqKTVUA_osjxzE2/view', Lock:false, week:0}, 
    { id: '3' , Type: 'Design', Title:'O Desenvolvimento na EJCM', Monitor:'Lucas Pinheiro',  Image:'', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '4' , Type: 'Design', Title:'UI Design I', Monitor:'Camila',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '5' , Type: 'Design', Title:'UX Design II', Monitor:'Anielly',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '6' , Type: 'Design', Title:'Figma I', Monitor:'Paula',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '7' , Type: 'Design', Title:'Imergir: Double Diamond e Pesquisa', Monitor:'Daniel X',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '8' , Type: 'Design', Title:'Definir: Persona e Proposta de Valor', Monitor:'Lorenzzo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '9' , Type: 'Design', Title:'Criar: User Flow e User Stories', Monitor:'Patricia',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '10' , Type: 'Design', Title:'Wordpress I', Monitor:'Leonardo', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '11' , Type: 'Design', Title:'Movimento Empresa Junior', Monitor:'Danielly Muniz',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '12' , Type: 'Design', Title:'Diversidade e Inclusão', Monitor:'Vinny & Ani',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '13' , Type: 'Design', Title:'WordPress II', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '14' , Type: 'Design', Title:'UI Design II', Monitor:'Luciano',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '15' , Type: 'Design', Title:'Design Visual', Monitor:'Gustavo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '16' , Type: 'Design', Title:'Figma II', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '17' , Type: 'Design', Title:'Figma (Workshop)', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '18' , Type: 'Design', Title:'Figma III', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0},
]

export const AulasDev = [
    { id: '1' ,  Type: 'Dev', Title:'Introdução a Computação', Monitor:'Vinny',  Image:'', Link:'lKQ0lleMXtk', PDF:'', Lock:true, week:0}, 
    { id: '30' ,  Type: 'Dev', Title:'Noções de Figma', Monitor:'Gustavo',  Image: '', Link:'A7c1wJZRxV0', PDF:'', Lock:true, week:0}, 
    { id: '2' ,  Type: 'Dev', Title:'Git e Ambiente Dev', Monitor:'Iago Cesar',  Image: '', Link:'A7c1wJZRxV0', PDF:'', Lock:true, week:0}, 
    { id: '3' ,  Type: 'Dev', Title:'HTML/CSS I', Monitor:'Bruna Nobrega',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '4' ,  Type: 'Dev', Title:'HTML/CSS II', Monitor:'Leonardo',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '5' ,  Type: 'Dev', Title:'Scrum', Monitor:'Miguel Ângelo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '6' ,  Type: 'Dev', Title:'Marketing e Vendas', Monitor:'Iago Cesar',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '7' ,  Type: 'Dev', Title:'Javascript I', Monitor:'Miguel Ângelo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '8' ,  Type: 'Dev', Title:'Javascript II - POO', Monitor:'Gustavo Breda', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '9' ,  Type: 'Dev', Title:'Typescript', Monitor:'Danilo', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '10' ,  Type: 'Dev', Title:'Wordpress I', Monitor:'Leonardo',Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '11' ,  Type: 'Dev', Title:'Movimento Empresa Junior', Monitor:'Danielly Muniz', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '12' ,  Type: 'Dev', Title:'Diversidade e Inclusão', Monitor:'Vinny & Ani',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '13' ,  Type: 'Dev', Title:'WordPress II', Monitor:'Instrutor', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '14' ,  Type: 'Dev', Title:'Introdução ao React', Monitor:'Bruna Nobrega',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '15' ,  Type: 'Dev', Title:'React Native', Monitor:'Lucas Stefano',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '16' ,  Type: 'Dev', Title:'Styled Components', Monitor:'Franscisco',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '17' ,  Type: 'Dev', Title:'Modelagem BD', Monitor:'Socrates de Sousa',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '18' ,  Type: 'Dev', Title:'Introdução ao Backend e Models', Monitor:'Danilo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '19' ,  Type: 'Dev', Title:'Rotas, Controllers e Seeders', Monitor:'Gabriel Araújo', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '20' ,  Type: 'Dev', Title:'Components & DataBinding', Monitor:'Instrutor', Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '21' ,  Type: 'Dev', Title:'Middlewares & Validation', Monitor:'Gabriel Araújo',  Image: '', Link:'', PDF:'', Lock:true, week:0},
    { id: '22' ,  Type: 'Dev', Title:'Formulários, Máscaras e Validação', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '23' ,  Type: 'Dev', Title:'Autenticação', Monitor:'Lucas Al Alam', Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '24' ,  Type: 'Dev', Title:'Rotas', Monitor:'Gustavo Breda',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '25' ,  Type: 'Dev', Title:'Nodemailer & Multer', Monitor:'Socrates de Souza',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '26' ,  Type: 'Dev', Title:'Hooks', Monitor:'Lucas Stefano',  IImage: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '27' ,  Type: 'Dev', Title:'Ferramentas Nativas', Monitor:'Instrutor',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '28' ,  Type: 'Dev', Title:'Integração I', Monitor:'Gabriel Ayres',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
    { id: '29' ,  Type: 'Dev', Title:'Integração II', Monitor:'Gabriel Ayres',  Image: '', Link:'', PDF:'', Lock:true, week:0}, 
  
]